// Predefined fuel companies that will be available to all users
export const predefinedFuelCompanies = [
  'Shell',
  'BP',
  'Exxon',
  'Mobil',
  'Chevron',
  'Texaco',
  'Esso',
  'Caltex',
  'Petro-Canada',
  'Sinopec',
  'PetroChina',
  'Total',
  '7-Eleven',
  'Costco',
  'Circle K',
  'ARCO',
  // Japanese fuel companies
  'ENEOS',
  'Idemitsu',
  'Cosmo Oil',
  'Showa Shell',
  'Apollostation',
];

// Predefined fuel types that will be available to all users
export const predefinedFuelTypes = [
  'Regular Gasoline',
  'Premium Gasoline',
  'Super Premium Gasoline',
  'Diesel',
  'Premium Diesel',
  'Bio Diesel',
  'E85 Ethanol',
  'E10 Ethanol',
  'CNG (Compressed Natural Gas)',
  'LPG (Liquefied Petroleum Gas)',
  'Electric',
  'Hydrogen',
  'Aviation Fuel',
  'Marine Fuel',
  'Racing Fuel',
  'Other'
];

// Predefined expense categories that will be available to all users
export const predefinedExpenseCategories = [
  // Maintenance & Service
  'Regular Service',
  'Oil Change',
  'Tire Replacement',
  'Tire Repair',
  'Tire Rotation',
  'Tire Balancing',
  'Wheel Alignment',
  'Brake Service',
  'Brake Pad Replacement',
  'Brake Fluid Change',
  'Engine Repair',
  'Engine Tune-up',
  'Engine Oil Filter',
  'Transmission Service',
  'Transmission Repair',
  'Transmission Fluid Change',
  'Battery Replacement',
  'Battery Testing',
  'Air Filter',
  'Cabin Air Filter',
  'Fuel Filter',
  'Spark Plugs',
  'Spark Plug Wires',
  'Coolant Service',
  'Coolant Flush',
  'Radiator Repair',
  'Thermostat Replacement',
  'Water Pump Replacement',
  'Exhaust Repair',
  'Muffler Replacement',
  'Catalytic Converter',
  'Suspension Repair',
  'Shock Absorber Replacement',
  'Strut Replacement',
  'Spring Replacement',
  'Electrical Repair',
  'Alternator Replacement',
  'Starter Replacement',
  'Fuse Replacement',
  'Wiring Repair',
  'Air Conditioning Service',
  'AC Compressor',
  'AC Refrigerant',
  'Heater Repair',
  'Windshield Wiper Blades',
  'Windshield Washer Fluid',
  'Power Steering Service',
  'Belt Replacement',
  'Hose Replacement',
  'Timing Belt',
  'Clutch Repair',
  'Clutch Replacement',
  'CV Joint Repair',
  'Differential Service',
  'Fuel Pump Replacement',
  'Fuel Injector Cleaning',
  'Carburetor Service',
  
  // Legal & Registration
  'Vehicle Registration',
  'Registration Renewal',
  'License Renewal',
  'Inspection Fee',
  'Safety Inspection',
  'Emissions Test',
  'Smog Check',
  'Road Tax',
  'Vehicle Tax',
  'Tag Renewal',
  'Title Transfer',
  'Notary Fees',
  'DMV Fees',
  
  // Insurance & Protection
  'Insurance Premium',
  'Insurance Deductible',
  'Comprehensive Coverage',
  'Collision Coverage',
  'Liability Insurance',
  'Gap Insurance',
  'Extended Warranty',
  'Service Contract',
  'Roadside Assistance',
  'AAA Membership',
  
  // Accidents & Damage
  'Accident Repair',
  'Collision Damage',
  'Vandalism Repair',
  'Theft Recovery',
  'Glass Replacement',
  'Windshield Replacement',
  'Window Repair',
  'Paint Repair',
  'Scratch Repair',
  'Dent Repair',
  'Body Work',
  'Frame Repair',
  'Bumper Repair',
  'Mirror Replacement',
  'Headlight Replacement',
  'Tail Light Replacement',
  
  // Cleaning & Appearance
  'Car Wash',
  'Detailing',
  'Interior Detailing',
  'Exterior Detailing',
  'Waxing',
  'Paint Protection',
  'Ceramic Coating',
  'Interior Cleaning',
  'Carpet Cleaning',
  'Seat Cleaning',
  'Dashboard Treatment',
  'Leather Conditioning',
  
  // Accessories & Upgrades
  'Car Accessories',
  'Audio System',
  'Speaker Installation',
  'Amplifier Installation',
  'Subwoofer Installation',
  'Navigation System',
  'Dash Cam',
  'Backup Camera',
  'Security System',
  'Car Alarm',
  'Remote Start',
  'Keyless Entry',
  'Performance Upgrades',
  'Turbo Installation',
  'Exhaust Upgrade',
  'Suspension Upgrade',
  'Cold Air Intake',
  'Performance Chip',
  'Tinting',
  'Window Tinting',
  'Sunroof Installation',
  'Roof Rack',
  'Trailer Hitch',
  'Running Boards',
  'Bull Bar',
  'Mud Flaps',
  'Floor Mats',
  'Seat Covers',
  'Steering Wheel Cover',
  'Phone Mount',
  'USB Charger',
  'Inverter',
  'Jump Starter',
  'Tool Kit',
  'Emergency Kit',
  
  // Daily Operations
  'Parking Fees',
  'Parking Meter',
  'Parking Garage',
  'Monthly Parking',
  'Tolls',
  'Bridge Toll',
  'Highway Toll',
  'Congestion Charge',
  'Valet Service',
  'Car Rental',
  'Rental Car',
  'Rideshare',
  'Taxi',
  'Public Transport',
  
  // Violations & Penalties
  'Traffic Fine',
  'Speeding Ticket',
  'Parking Ticket',
  'Red Light Ticket',
  'Moving Violation',
  'Equipment Violation',
  'Late Fees',
  'Court Costs',
  'Attorney Fees',
  'Traffic School',
  'Defensive Driving Course',
  
  // Major Expenses
  'Vehicle Purchase',
  'Down Payment',
  'Trade-in Difference',
  'Loan Payment',
  'Lease Payment',
  'Balloon Payment',
  'Sales Tax',
  'Documentation Fee',
  'Dealer Fee',
  'Finance Charges',
  'Interest Payment',
  'Gap Protection',
  'Vehicle Depreciation',
  
  // Fuel & Energy
  'Fuel Additives',
  'Octane Booster',
  'Fuel System Cleaner',
  'Electric Charging',
  'Home Charging Station',
  'Public Charging',
  'Fast Charging',
  'Charging Membership',
  'Solar Panel Installation',
  'Generator Fuel',
  
  // Professional Services
  'Mechanic Labor',
  'Diagnostic Fee',
  'Shop Supplies',
  'Environmental Fee',
  'Disposal Fee',
  'Towing Service',
  'Flatbed Towing',
  'Roadside Service',
  'Jump Start Service',
  'Lockout Service',
  'Tire Change Service',
  'Mobile Mechanic',
  'Delivery Fee',
  'Pickup Fee',
  
  // Storage & Facilities
  'Storage Fees',
  'Garage Rental',
  'Covered Parking',
  'Car Port',
  'Vehicle Storage',
  'Seasonal Storage',
  'Climate Controlled Storage',
  
  // Emergency & Unexpected
  'Emergency Repair',
  'Roadside Emergency',
  'After Hours Service',
  'Holiday Surcharge',
  'Expedited Service',
  'Rush Delivery',
  'Emergency Towing',
  'Emergency Parts',
  'Temporary Transportation',
  'Rental Car (Emergency)',
  'Hotel Stay (Travel)',
  'Meals (Travel)',
  
  // Specialty & Custom
  'Custom Fabrication',
  'Restoration Work',
  'Antique Car Parts',
  'Classic Car Service',
  'Show Car Preparation',
  'Racing Preparation',
  'Track Day Fees',
  'Driver Training',
  'Performance Testing',
  'Dyno Testing',
  'Alignment Specs',
  'Custom Paint',
  'Vinyl Wrap',
  'Decals',
  'Graphics',
  'Chrome Work',
  'Powder Coating',
  'Sandblasting',
  'Welding',
  'Fabrication',
  
  // Miscellaneous
  'Miscellaneous',
  'Other',
  'Unknown',
  'Reimbursable Expense',
  'Business Expense',
  'Personal Use',
  'Gift',
  'Donation',
  'Charity',
  'Research',
  'Testing',
  'Experimental',
  'Prototype',
  'Development'
];

// Predefined income categories that will be available to all users
export const predefinedIncomeCategories = [
  'Ride Sharing',
  'Delivery Services',
  'Taxi Services',
  'Car Rental',
  'Vehicle Sale',
  'Insurance Claim',
  'Fuel Reimbursement',
  'Mileage Reimbursement',
  'Business Use',
  'Freelance Driving',
  'Other'
];
