/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Enhanced light mode color palette with improved contrast
        light: {
          bg: '#ffffff',
          'bg-secondary': '#f8fafc',
          'bg-tertiary': '#f1f5f9',
          surface: '#ffffff',
          'surface-elevated': '#ffffff',
          'surface-hover': '#f1f5f9',
          border: '#e2e8f0',
          'border-light': '#f1f5f9',
          text: '#0f172a',        /* Much darker primary text */
          'text-secondary': '#1e293b',  /* Darker secondary text */
          'text-muted': '#334155',      /* Darker muted text */
          'text-light': '#475569',      /* Darker light text */
        },
        // Dark mode colors (existing + enhanced)
        dark: {
          bg: '#0a0a0a',
          'bg-secondary': '#111111',
          'bg-tertiary': '#1a1a1a',
          surface: '#111111',
          'surface-elevated': '#1a1a1a',
          'surface-hover': '#2a2a2a',
          card: '#1a1a1a',
          border: '#2a2a2a',
          'border-light': '#1a1a1a',
          text: '#ededed',
          'text-secondary': '#a1a1a1',
          'text-muted': '#6b7280',
          'text-light': '#4b5563',
        },
        // Semantic colors for both light and dark modes
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
          950: '#172554',
        },
        secondary: {
          50: '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: '#0f172a',
          950: '#020617',
        },
        success: {
          50: '#ecfdf5',
          100: '#d1fae5',
          200: '#a7f3d0',
          300: '#6ee7b7',
          400: '#34d399',
          500: '#10b981',
          600: '#059669',
          700: '#047857',
          800: '#065f46',
          900: '#064e3b',
          950: '#022c22',
        },
        warning: {
          50: '#fffbeb',
          100: '#fef3c7',
          200: '#fde68a',
          300: '#fcd34d',
          400: '#fbbf24',
          500: '#f59e0b',
          600: '#d97706',
          700: '#b45309',
          800: '#92400e',
          900: '#78350f',
          950: '#451a03',
        },
        error: {
          50: '#fef2f2',
          100: '#fee2e2',
          200: '#fecaca',
          300: '#fca5a5',
          400: '#f87171',
          500: '#ef4444',
          600: '#dc2626',
          700: '#b91c1c',
          800: '#991b1b',
          900: '#7f1d1d',
          950: '#450a0a',
        },
        // Enhanced theme-aware colors
        theme: {
          bg: 'var(--background)',
          'bg-secondary': 'var(--surface)',
          'bg-elevated': 'var(--surface-elevated)',
          'bg-hover': 'var(--surface-hover)',
          text: 'var(--foreground)',
          'text-secondary': 'var(--muted-foreground)',
          'text-muted': 'var(--muted)',
          border: 'var(--border)',
          'border-light': 'var(--border-light)',
          primary: 'var(--primary)',
          'primary-foreground': 'var(--primary-foreground)',
          secondary: 'var(--secondary)',
          'secondary-foreground': 'var(--secondary-foreground)',
          accent: 'var(--accent)',
          'accent-foreground': 'var(--accent-foreground)',
          destructive: 'var(--destructive)',
          'destructive-foreground': 'var(--destructive-foreground)',
          success: 'var(--success)',
          'success-foreground': 'var(--success-foreground)',
          warning: 'var(--warning)',
          'warning-foreground': 'var(--warning-foreground)',
          info: 'var(--info)',
          'info-foreground': 'var(--info-foreground)',
          card: 'var(--card-background)',
          'card-border': 'var(--card-border)',
          input: 'var(--input-background)',
          'input-border': 'var(--input-border)',
          'input-border-focus': 'var(--input-border-focus)',
          'input-placeholder': 'var(--input-placeholder)',
        },
      },
      boxShadow: {
        'light-sm': '0 1px 2px 0 rgb(0 0 0 / 0.05)',
        'light': '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
        'light-md': '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
        'light-lg': '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
        'light-xl': '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
        'theme-card': 'var(--card-shadow)',
        'theme-card-hover': 'var(--card-shadow-hover)',
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
      fontFamily: {
        sans: ['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'sans-serif'],
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
      },
      borderRadius: {
        'xl': '0.875rem',
        '2xl': '1.125rem',
      },
    },
  },
  plugins: [],
};
